name: Laravel CI/CD Pipeline (Docker)

on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_mysql, xml, curl

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Laravel using Docker on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.70.41.71
          username: azureuser
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/html/laravel-project

            echo "Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Stopping old containers..."
            docker-compose down -v

            echo "Building and starting containers..."
            docker-compose up -d --build

            echo "Running Laravel commands inside container..."
            docker exec laravel-app php artisan migrate --force
            docker exec laravel-app php artisan config:clear
            docker exec laravel-app php artisan cache:clear
            docker exec laravel-app php artisan route:cache

            echo "Deployment completed successfully 🚀"
